apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: basedequestions-ingress
  namespace: request
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-request-buffering: off
spec:
  rules:
    - host: HOST_PLACEHOLDER
      http:
        paths:

          # Accès à l'application principale
          - path: /
            backend:
              serviceName: basedequestions
              servicePort: 8000
