apiVersion: v1
kind: Service
metadata:
  name: basedequestions-media
  labels:
    app: basedequestions
spec:
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: basedequestions
  clusterIP: None
