apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: request

bases:
  - ../../base/

resources:
  - pvc.yml
  - media-pvc.yml
  - ingress.yml


# Labels communs à toutes les ressources dans cet overlay
commonLabels:
  environment: prod


# Images à utiliser pour cet environnement (staging)
images:
  - name: gitlab.sciences-po.fr:4567/cdspit/base-de-questions/basedequestions
    newTag: 'prod'


patchesStrategicMerge:
  - elasticsearch-patch.yml
