apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: request
spec:
  replicas: 1
  selector:
    matchLabels:
      component: elasticsearch
  template:
    metadata:
      labels:
        component: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: elasticsearch:7.17.10
          env:
            - name: discovery.type
              value: 'single-node'
            - name: cluster.name
              value: 'elasticsearch'
            - name: bootstrap.memory_lock
              value: 'true'
            - name: ES_JAVA_OPTS
              value: '-Xms512m -Xmx512m'
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
      volumes:
        - name: config-volume
          configMap:
            name: elasticsearch-config
