apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      component: elasticsearch
  template:
    metadata:
      labels:
        component: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: elasticsearch:7.17.10
          env:
            - name: discovery.type
              value: 'single-node'
            - name: cluster.name
              value: 'elasticsearch'
            - name: bootstrap.memory_lock
              value: 'true'
            - name: ES_JAVA_OPTS
              value: '-Xms512m -Xmx512m'
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /var/lib/elasticsearch  # Le chemin où Elasticsearch stocke ses données
            - name: elasticsearch-config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml  # Remplacer le fichier de config par celui du ConfigMap
              subPath: elasticsearch.yml  # Cela permet de monter un fichier spécifique du ConfigMap
      volumes:
        - name: elasticsearch-data
          persistentVolumeClaim:
            claimName: elasticsearch-pvc  # Le PVC que nous avons créé précédemment
        - name: elasticsearch-config
          configMap:
            name: elasticsearch-config  # Le ConfigMap contenant ton fichier de config
