apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: basedequestions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basedequestions
      component: db
      environment: pprd
  template:
    metadata:
      labels:
        app: basedequestions
        component: db
        environment: pprd
    spec:
      containers:
        - name: postgres
          image: postgres:13-alpine  # Version de PostgreSQL
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_DB
          ports:
            - containerPort: 5432     # Expose le port de PostgreSQL
          volumeMounts:
            - name: db-vol
              mountPath: /var/lib/postgresql/data  # Répertoire pour les données
      volumes:
        - name: db-vol
          persistentVolumeClaim:
            claimName: db-pvc            # Assurez-vous que ce PVC existe
