apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: request

# Les ressources que tu veux inclure
resources:
  - basedequestions/deployment.yml
  - basedequestions/service.yml
  - basedequestions/ingress.yml
  - elasticsearch/deployment.yml
  - elasticsearch/service.yml
  - elasticsearch/elasticsearch-pvc.yml
  - elasticsearch/configmap.yml
  - db/deployment.yml
  - db/service.yml
  - db/db-pvc.yml
  - nginx-media/deployment.yml
  - nginx-media/service.yml
  - nginx-media/nginx-configmap.yml
  - nginx-media/media-pvc.yml




secretGenerator:
  - name: basedequestions-secret
    literals:
      - DJANGO_SECRET_KEY=your-secret-key-here
