apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-media
  namespace: basedequestions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-media
  template:
    metadata:
      labels:
        app: nginx-media
    spec:
      containers:
        - name: nginx-media
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf  # Monte uniquement le fichier nginx.conf du ConfigMap
            - name: media-volume
              mountPath: /usr/share/nginx/html/media/  # Le répertoire où NGINX servira les fichiers media
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config  # Référence au ConfigMap créé
            items:
              - key: nginx.conf
                path: nginx.conf  # Le fichier sera monté à cet endroit dans le container
        - name: media-volume
          persistentVolumeClaim:
            claimName: media-pvc  # Nom du PVC partagé avec l'autre déploiement
