apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-media
  template:
    metadata:
      labels:
        app: nginx-media
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          volumeMounts:
            - name: media-volume
              mountPath: /usr/share/nginx/html/media
      volumes:
        - name: media-volume
          persistentVolumeClaim:
            claimName: media-pvc
