apiVersion: networking.k8s.io/v1  # Utilisation de la nouvelle API
kind: Ingress
metadata:
  name: basedequestions-ingress
  namespace: basedequestions
  annotations:
    ingress.kubernetes.io/rewrite-target: / # Réécrit tous les chemins pour qu'ils commencent à la racine
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "180"

spec:
  rules:
    - host: base-de-questions-pprd.cdsp.sciences-po.fr
      http:
        paths:
          # Ne pas réécrire les chemins /media
          - path: /media(/|$)(.*)
            pathType: Prefix  # Nouveau champ requis pour la version v1
            backend:
              service:
                name: basedequestions
                port:
                  number: 8000

          # Réécrire les autres routes
          - path: /
            pathType: Prefix  # Nouveau champ requis pour la version v1
            backend:
              service:
                name: basedequestions
                port:
                  number: 8000
