apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: basedequestions-ingress
  namespace: basedequestions
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "180"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      # Configuration spécifique pour servir les fichiers médias
      location /media/ {
        alias /app/media/;
        autoindex on;
      }
spec:
  rules:
    - host: base-de-questions-pprd.cdsp.sciences-po.fr
      http:
        paths:
          - path: /media/
            backend:
              serviceName: nginx-ingress-controller
              servicePort: 80
          - path: /
            backend:
              serviceName: basedequestions
              servicePort: 8000
