apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: basedequestions-ingress
  namespace: basedequestions
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "180"
    # Applique le rewrite pour les autres requêtes mais laisse les /media/ intactes
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: base-de-questions-pprd.cdsp.sciences-po.fr
      http:
        paths:
          # Cette règle gère les fichiers /media/ et les redirige sans réécriture
          - path: /media/(.*)
            backend:
              serviceName: basedequestions
              servicePort: 8000

          # Cette règle applique le rewrite target sur les autres chemins
          - path: /(.+)
            backend:
              serviceName: basedequestions
              servicePort: 8000
