apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: basedequestions-ingress
  namespace: request
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-request-buffering: off
spec:
  rules:
    - host: request-pprd.sciencespo.fr
      http:
        paths:
          # Accès aux fichiers médias, via le service NGINX
          - path: /media/
            backend:
              serviceName: nginx-media
              servicePort: 80  # Port exposé par le service NGINX

          # Accès à l'application principale
          - path: /
            backend:
              serviceName: basedequestions
              servicePort: 8000
