apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: basedequestions-ingress
  namespace: basedequestions
spec:
  rules:
    - host: base-de-questions-pprd.cdsp.sciences-po.fr
      http:
        paths:
          - path: /media/
            backend:
              serviceName: nginx-media-service
              servicePort: 80
          - path: /
            backend:
              serviceName: basedequestions
              servicePort: 8000
