#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: basedequestions-ingress
#spec:
#  rules:
#  - host: base-de-questions-pprd.cdsp.sciences-po.fr
#    http:
#      paths:
#      - path: /
#        pathType: Prefix
#        backend:
#          service:
#            name: basedequestions
#            port:
#              number: 8000
