apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: basedequestions-ingress
  namespace: basedequestions
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
spec:
  rules:
    - host: base-de-questions-pprd.cdsp.sciences-po.fr
      http:
        paths:
          # Accès aux fichiers médias, via le service NGINX
          - path: /media/
            backend:
              serviceName: nginx-media  # Change de `basedequestions` à `nginx-media` pour utiliser le service NGINX
              servicePort: 80  # Port exposé par le service NGINX (80 ou autre selon ta config)

          # Accès à l'application principale
          - path: /
            backend:
              serviceName: basedequestions
              servicePort: 8000
